EDA - Visits Week Over Week
========================================================

```{r options, echo=FALSE, warning=FALSE, results='hide',message=FALSE}
library(plyr)
library(ggplot2)
library(lme4)
library(glmnet)
library(MASS)
library(knitr)

opts_chunk$set(cache=TRUE, autodep=TRUE, echo=T, warning=FALSE, message=FALSE)
#setwd("Code")
library(ROCR) 
source("Auc_Accuracy.R")

```

Visits
------------
Important for you to run weeklyvisit_manipulate.R first to create data file...

```{r load list}
load("../Data/ProcessedVisits.Rdata")
```

Here is what our survival curve looks like - it is a cumulative distribution function

```{r survival}
curve <- ddply(train[!train$cohort,], 
               .(week,weeks), summarize, 
               numrow = length(user_hash),
               noret = 1-sum(ret_flag)/numrow)

ggplot(curve, aes(x=weeks, y=noret, color=week))+geom_point()+stat_smooth()+ggtitle("probability of no return by weeks since first")

```

```{r fit gamma}
criterion  <- function(par, week, fraction){ 
                  cdf <- pgamma(week, shape=par[1], scale=par[2]) 
                  sum((fraction-cdf)^2/cdf) # or some other function 
                  } 
cont <- optim(par=c(1,1),criterion, week=curve$weeks[curve$weeks], fraction=curve$noret[curve$weeks])
cont$par

curve$ex <- pgamma(curve$weeks,shape=cont$par[1],scale=cont$par[2])
head(curve)

ggplot(curve,aes(x=weeks,y=noret))+geom_point()+geom_line(aes(y=ex))
ggplot(curve,aes(x=noret,y=ex, color=weeks))+geom_point()+
  scale_y_continuous(limit=c(0.4,.8))+
  scale_x_continuous(limit=c(0.4,.8))


look <- (ddply(curve, .(weeks), summarize, median = median(noret), avg = mean(noret)))
look$gam <- with(look, pgamma(weeks,shape=cont$par[1],scale=cont$par[2]))
head(look,10)
tail(look,10)
look$ret <- 1-look$gam 
merged <- look[,c("weeks","ret","gam")]
train <- merge(train,merged)
test <- merge(test,merged)
submit <- merge(submit,merged)
```

```{r logistic on prior visit}

head(train)

unique(train$flag_first_week)

visit.glm <- glm(ret_flag~visit_p+purch_p+cohort+gam-1,train, family="binomial")
summary(visit.glm)
pred.visit.glm <- predict(visit.glm, newdata=test, type="response")
auc.fn(pred.visit.glm,test$ret_flag)
plotauc.fn(pred.visit.glm,test$ret_flag)
predic <- prediction(pred.visit.glm,test$ret_flag)
acc.perf <- performance(predic, "acc")
ind = which.max( slot(acc.perf, "y.values")[[1]] )
acc = slot(acc.perf, "y.values")[[1]][ind]
cutoff = slot(acc.perf, "x.values")[[1]][ind]
print(c(accuracy= acc, cutoff = cutoff))
hist(pred.visit.glm)

```



```{r submit}
pred.visit.submit <- predict(visit.glm, newdata=submit, type="response")
visited.submit <- pred.visit.submit>cutoff
submit.df <- data.frame(submit$user_hash,visited.submit,pred.visit.submit)
names(submit.df) <- c("user_hash","type","pred.visit")
nrow(submit)
```

```{r cosine similarlity}
cosine <- read.csv("../Data/cosine_sim.csv",stringsAsFactors=F)
submitted <- merge(cosine,submit.df, by.x="USER_ID_hash",by.y="user_hash", all.x=T)
submitted$type[is.na(submitted$type)]<-F
submitted[submitted$type==F,"PURCHASED_COUPONS"]<-""
submitted <- submitted[,1:2]
write.csv(submitted, "../Data/cosine_visit.csv",row.names=FALSE)
```
